### ISSUE TITLE
is invalid: spec.template.spec.containers[0].image: Required value" pkg=function-controller

### ISSUE THREAD

**Issue by engmsaleh** [defrox/kubeless-custom-runtime#1]
I have followed your tutorial and also the official one and I'm always getting the same error when I try to use my custom runtime, the pod for the function crashes and it have the following error

```
time="2019-05-27T15:29:55Z" level=info msg="Processing change to Function lambda/get-local-banks" pkg=function-controller
time="2019-05-27T15:29:56Z" level=error msg="Function can not be created/updated: Deployment.apps \"get-local-banks\" is invalid: spec.template.spec.containers[0].image: Required value" pkg=function-controller
time="2019-05-27T15:29:56Z" level=error msg="Error processing lambda/get-local-banks (giving up): Deployment.apps \"get-local-banks\" is invalid: spec.template.spec.containers[0].image: Required value" pkg=function-controller
ERROR: logging before flag.Parse: E0527 15:29:56.541207       1 function_controller.go:185] Deployment.apps "get-local-banks" is invalid: spec.template.spec.containers[0].image: Required value
```
I think it might be a missing thing
here is my entry

```
{
	"ID": "pythonWithDep",
	"compiled": false,
	"versions": [{
		"name": "python37",
		"version": "3.7",
		"runtimeImage": "343468943582.dkr.ecr.eu-west-1.amazonaws.com/custom-python-runtime:latest",
		"initImage": "python:3.7"
	}],
	"depName": "requirements.txt",
	"fileNameSuffix": ".py"
}
```

**Comment by defrox** [comment]
Have you created your own docker image and updated kubeless.py to python 3.7? When does it crashes, when deploying the custom image or when calling the function? Do you have a repo to take a look?

**Comment by engmsaleh** [comment]
Hi @defrox 
- I didn't update **kubeless.py**
- I think it was crashing when it was pulling the image or after I don't know for sure

After some assistance here 
https://github.com/kubeless/kubeless/issues/939
I have got it working with this configuration

```
{
	"ID": "gpupython",
	"depName": "requirements.txt",
	"fileNameSuffix": ".py",
	"versions": [{
		"images": [{
			"command": "pip install --prefix=$KUBELESS_INSTALL_VOLUME -r $KUBELESS_DEPS_FILE",
			"image": "python:3.7",
			"phase": "installation"
		}, {
			"env": {
				"PYTHONPATH": "$(KUBELESS_INSTALL_VOLUME)/lib/python3.7/site-packages:$(KUBELESS_INSTALL_VOLUME)"
			},
			"image": "engmsaleh/python-with-dep:1",
			"phase": "runtime"
		}],
		"name": "gpupython37",
		"version": "3.7"
	}]
}
```

I don't know why exactly the one you suggested and the one from official documentation, never worked for me

**Comment by defrox** [comment]
Hi @engmsaleh, thanks for the tip! I have tried my solution with the python 3.6 runtime as initImage and did work, but not with python 3.7. I will definitely give it a try using your solution!
